image:
  file: .gitpod-dockerfile
tasks:
  - init: |
      cabal update
      cabal install implicit-hie 
      stack init
      stack build
      stack setup
    command: |
      stack test
vscode:
  extensions:
    - haskell.haskell
